[package]
name = "deepseek-sdk"
version = "0.1.0"
edition = "2024"
authors = ["happyboy <superhappyboy1995@gmail.com>"]
description = "deepseek sdk"
keywords = ["deepseek", "AI"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/0xhappyboy/deepseek-sdk"

[dependencies]
